### ISSUE TITLE
Moving akka-persistence-hazelcast:1.0 to work with external hazelcast client

### ISSUE THREAD

**Issue by danny-lesnik** [sorokinigor/akka-persistence-hazelcast#10]
I would like to change current implementation  akka-persistence-hazelcast:1.0 to work with external hazelcast cluster.

So I changed client implementation in HazelcastExtention.scala with the following code:

```
val hazelcast: HazelcastInstance = {
    val classLoader = Thread.currentThread().getContextClassLoader
    val clientConfig = new XmlClientConfigBuilder("hazelcast-client.xml").build
    clientConfig.setClassLoader(classLoader)
    val serializationConfig = clientConfig.getSerializationConfig
    serializationConfig.addSerializerConfig(createSerializationConfig(classOf[PersistentRepr]))
    serializationConfig.addSerializerConfig(createSerializationConfig(classOf[PersistenceSnapshot]))
    HazelcastClient.newHazelcastClient(clientConfig)
  }
```
but when I run the code, I'm getting exception:

```
[ERROR] [12/03/2017 11:43:06.506] [application-akka.actor.default-dispatcher-4] [akka://application/user/hazelcastActor] Persistence failure when replaying events for persistenceId [hazelcastActor]. Last known sequence number [0]
com.hazelcast.core.HazelcastException: java.util.concurrent.ExecutionException: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: com.vanilla.actor.hazelcast.journal.LongExtractor$
	at com.hazelcast.client.proxy.ClientMapProxy.aggregate(ClientMapProxy.java:1343)
	at com.hazelcast.client.proxy.ClientMapProxy.aggregate(ClientMapProxy.java:1316)
	at com.vanilla.actor.hazelcast.journal.MapJournal$$anonfun$asyncReadHighestSequenceNr$1.apply$mcJ$sp(MapJournal.scala:145)
	at com.vanilla.actor.hazelcast.journal.MapJournal$$anonfun$asyncReadHighestSequenceNr$1.apply(MapJournal.scala:139)
	at com.vanilla.actor.hazelcast.journal.MapJournal$$anonfun$asyncReadHighestSequenceNr$1.apply(MapJournal.scala:139)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: com.vanilla.actor.hazelcast.journal.LongExtractor$
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolve(ClientInvocationFuture.java:66)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:246)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: com.vanilla.actor.hazelcast.journal.LongExtractor$
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:224)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:251)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
	at com.hazelcast.mapreduce.aggregation.impl.AcceptAllSupplier.readData(AcceptAllSupplier.java:77)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:151)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:104)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:54)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:251)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
	at com.hazelcast.mapreduce.aggregation.impl.PredicateSupplier.readData(PredicateSupplier.java:90)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:151)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:104)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:54)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:251)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
	at com.hazelcast.mapreduce.aggregation.impl.SupplierConsumingMapper.readData(SupplierConsumingMapper.java:84)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:151)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:104)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:54)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:172)
	at com.hazelcast.client.impl.protocol.task.mapreduce.MapReduceForMapMessageTask.getMapper(MapReduceForMapMessageTask.java:64)
	at com.hazelcast.client.impl.protocol.task.mapreduce.AbstractMapReduceTask.startSupervisionTask(AbstractMapReduceTask.java:111)
	at com.hazelcast.client.impl.protocol.task.mapreduce.AbstractMapReduceTask.processMessage(AbstractMapReduceTask.java:77)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:128)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	... 2 more
Caused by: java.lang.ClassNotFoundException
	at com.hazelcast.client.impl.protocol.ClientExceptionFactory$12.createException(ClientExceptionFactory.java:170)
	at com.hazelcast.client.impl.protocol.ClientExceptionFactory.createException(ClientExceptionFactory.java:622)
	at com.hazelcast.client.impl.protocol.ClientExceptionFactory.createException(ClientExceptionFactory.java:589)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.handleClientMessage(ClientInvocationServiceSupport.java:331)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.process(ClientInvocationServiceSupport.java:313)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.doRun(ClientInvocationServiceSupport.java:306)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.run(ClientInvocationServiceSupport.java:283)
 

```

I'm new to Hazelcast, but we need to use it as a persistence solution for state resilience. Anyway, I believe that this is good feature that your plugin will run on external client.

**Comment by sorokinigor** [comment]
@danny-lesnik Hi!
According to the stacktrace, it fails because of serialization issue: a class which is available on the client is not in the classpath on the server. [(Read more)](https://hazelcast.org/mastering-hazelcast/#sharing-classes)
Please, include akka-persistence-hazelcast.jar (with all its dependencies) in the classpath of each node in the cluster.
Good luck, let me know if you need further clarification!

**Comment by danny-lesnik** [comment]
I did what you have suggested. 
now I have the following scenario:

Those are my entities:
```
 @SerialVersionUID(1L)
  case class Increase(count:Int = 1)
  case object GetState
  case class CurrentState(count:Int)
```

This is my persistent actor
```
class HazelcastActor extends PersistentActor{

  var state = CurrentState(0)

  override def receiveRecover:Receive = {
    case msg:Increase => state = CurrentState(state.count+msg.count)
    case _ => unhandled("Unheld Message Received")
  }

  override def receiveCommand:Receive = {
    case msg:Increase => persist(msg)(m=> {state = CurrentState(state.count+m.count);println(state)})
    case GetState =>  sender() ! state
  }
  override def persistenceId = "hazelcastActor"
}
```
This is what I'm trying to do:
```
 val actor = system.actorOf(Props[HazelcastActor],"hazelcastActor")
  actor ! Increase(2)
  actor ! Increase(2)
  actor ! Increase(3)

  system.stop(actor)
  Thread.sleep(1000)
  val actor2 = system.actorOf(Props[HazelcastActor],"hazelcastActor")
  actor2 ! Increase(2)
  actor2 ! Increase(2)
  actor2 ! Increase(3)
```
This is how I initiate client:
```
  val hazelcast: HazelcastInstance = {
   // val hazelcastConfig = new ClasspathXmlConfig(config.getString("config-file"))
    val classLoader = Thread.currentThread().getContextClassLoader
    val clientConfig = new XmlClientConfigBuilder("hazelcast-client.xml").build
    clientConfig.setClassLoader(classLoader)
    val serializationConfig = clientConfig.getSerializationConfig
    serializationConfig.addSerializerConfig(createSerializationConfig(classOf[Increase]))
    serializationConfig.addSerializerConfig(createSerializationConfig(classOf[PersistentRepr]))
    serializationConfig.addSerializerConfig(createSerializationConfig(classOf[PersistenceSnapshot]))

    HazelcastClient.newHazelcastClient(clientConfig)
  }
```

This is the exception I'm getting, I believe that it has something to do with the way how data is serialised.:
```
CurrentState(2)
CurrentState(4)
CurrentState(7)
CurrentState(7)
[ERROR] [12/05/2017 00:41:26.261] [application-akka.actor.default-dispatcher-2] [akka://application/user/hazelcastActor] Persistence failure when replaying events for persistenceId [hazelcastActor]. Last known sequence number [0]
com.hazelcast.core.HazelcastException: java.util.concurrent.ExecutionException: com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable de-serializer for type 7. This exception is likely to be caused by differences in the serialization configuration between members or between clients and members.
	at com.hazelcast.client.proxy.ClientMapProxy.aggregate(ClientMapProxy.java:1343)
	at com.hazelcast.client.proxy.ClientMapProxy.aggregate(ClientMapProxy.java:1316)
	at com.vanilla.actor.hazelcast.journal.MapJournal$$anonfun$asyncReadHighestSequenceNr$1.apply$mcJ$sp(MapJournal.scala:145)
	at com.vanilla.actor.hazelcast.journal.MapJournal$$anonfun$asyncReadHighestSequenceNr$1.apply(MapJournal.scala:139)
	at com.vanilla.actor.hazelcast.journal.MapJournal$$anonfun$asyncReadHighestSequenceNr$1.apply(MapJournal.scala:139)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable de-serializer for type 7. This exception is likely to be caused by differences in the serialization configuration between members or between clients and members.
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolve(ClientInvocationFuture.java:66)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:246)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable de-serializer for type 7. This exception is likely to be caused by differences in the serialization configuration between members or between clients and members.
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.newHazelcastSerializationException(AbstractSerializationService.java:220)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:167)
	at com.hazelcast.mapreduce.impl.MapKeyValueSource.element(MapKeyValueSource.java:118)
	at com.hazelcast.mapreduce.impl.task.KeyValueSourceFacade.element(KeyValueSourceFacade.java:79)
	at com.hazelcast.mapreduce.impl.task.KeyValueSourceMappingPhase.executeMappingPhase(KeyValueSourceMappingPhase.java:48)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask.processMapping(MapCombineTask.java:140)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask.processPartitionMapping(MapCombineTask.java:309)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask.access$700(MapCombineTask.java:70)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask$PartitionBasedProcessor.processPartitions(MapCombineTask.java:361)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask$PartitionBasedProcessor.run(MapCombineTask.java:338)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ submitted from ------.(Unknown Source)
	at ------ Operation failed on node: [192.168.99.1]:5701 ------.notifyRemoteException(JobSupervisor.java:155)
	at com.hazelcast.mapreduce.impl.task.JobSupervisor.notifyRemoteException(JobSupervisor.java:155)
	at com.hazelcast.mapreduce.impl.MapReduceUtil.notifyRemoteException(MapReduceUtil.java:86)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask.handleProcessorThrowable(MapCombineTask.java:298)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask.access$500(MapCombineTask.java:70)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask$PartitionBasedProcessor.processPartitions(MapCombineTask.java:363)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask$PartitionBasedProcessor.run(MapCombineTask.java:338)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212)
	... 5 more 
```

**Comment by sorokinigor** [comment]
Your welcome!
